<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class News_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get project by project_id
     */
    function get_news($news_id)
    {
        return $this->db->get_where('news',array('news_id'=>$news_id))->row_array();
    }
        
    /*
     * Get all project
     */
    function get_all_news()
    {
        $this->db->order_by('news_id', 'desc');
        return $this->db->get('news')->result_array();
    }
        
    /*
     * function to add new project
     */
    function add_news($params)
    {
        $this->db->insert('news',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update project
     */
    function edit_news($news_id,$params)
    {
        $this->db->where('news_id',$news_id);
        return $this->db->update('news',$params);
    }
    
    /*
     * function to delete project
     */
    function delete_news($news_id)
    {
        return $this->db->delete('news',array('news_id'=>$news_id));
    }
}
